server/pastes/urls.py
from django.urls import path
from . import views
from .views import  PasteView, PasteDetail, PasteAddView

app_name = 'pastes'

urlpatterns = [
    path('', views.index, name = "index"),
    path('list/', PasteView.as_view(), name = "paste_list"),
    path('detail/<int:pk>', PasteDetail.as_view(), name = 'paste_detail'),
    path('add_paste/', views.PasteAddView, name = 'add_paste'),

]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.shortcuts import HttpResponse
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pastes/', include('pastes.urls')),
    path('user/', include('user.urls')),
    path('pastes/', include('django.contrib.auth.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='detail.html'), name='detail'),
    path('pastes/', include('social_django.urls', namespace='social')), 
    path('user/', include('social_django.urls', namespace='social')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'), 
]

server/user/urls.py
from django.urls import path
from . import views
from .views import register

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name = 'register'),
    path("password_reset", views.password_reset_request, name="password_reset"),

]

server/pastes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Paste(models.Model):  
    title = models.CharField(max_length = 200)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    content = models.TextField(default = '')
    language = models.CharField(max_length = 255, default = 'Java')

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        return reverse('detail')

class Language(models.Model):
    name = models.CharField(max_length = 255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail')

server/user/models.py
from django.db import models

# Create your models here.

server/pastes/forms.py
from django import forms
from .models import Paste, Language

choices = Language.objects.all().values_list('name', 'name')
choice_list = []

for item in choices:
    choice_list.append(item)
    
class PasteForm(forms.ModelForm):
    class Meta:
        model = Paste
        fields = ('title', 'language', 'content')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your title for paste'}),
            'language': forms.Select(choices= choice_list, attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'This place add your content'}),
        }

server/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

server/pastes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .models import Paste, Language
from .forms import  PasteForm
from django.views.generic import DetailView, ListView, CreateView

def index(request):
    return render(request, 'pastes/index.html')

class PasteView(ListView):
    model = Paste
    template_name = 'paste_list.html'

class PasteDetail(DetailView):
    model = Paste
    template_name = 'paste_detail.html'

def PasteAddView(request):
    form = PasteForm(request.POST or None)
    if request.method=='POST':
        title = request.POST['title']
        user = request.user
        content = request.POST['content']
        paste = Paste.objects.create(title = title, author = user, content = content)
        paste.save()
        return redirect('/')
    else:
        return render(request, 'paste_add.html', {'form': form})

class LanguageAddView(CreateView):
    model = Language

server/user/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import SignUpForm


def register(response):
    if response.method == "POST":
        form = SignUpForm(response.POST)
        if form.is_valid():
            form.save()
            return redirect("/user")
    else:
        form = SignUpForm()

    return render(response, "registration/register.html", {"form" : form})

def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "registration/password_reset_email.txt"
                    c = {
                    "email":user.email,
                    'domain':'127.0.0.1:8000',
                    'site_name': 'Website',
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "user": user,
                    'token': default_token_generator.make_token(user),
                    'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com' , [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect ("/password_reset/done/")
            messages.error(request, 'An invalid email has been entered.')
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="registration/password_reset.html", context={"password_reset_form":password_reset_form})

server/pastes/templates/pastes/detail.html
{% extends 'index.html' %}

{% if user.is_authenticated %}

    <h2>Welcome, {{ user.username }}!</h2>

{% else %}

    <h1>Register</h1>
    
{% endif %}

server/pastes/templates/pastes/index.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
    <head>
        <title>Copia PasteBin</title>
        <meta charset="utf-8">
        <link rel = "shourtcut icon" href = "{% static 'images/mr.png' %}" type = "mr/png">
        <link rel="stylesheet" href="{% static 'style/style.css' %}" type="text/css">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>

    <body>
        <div id = "main">
            {% if user.is_authenticated %}
                <h2>Welcome, {{ user.username }}!</h2>
                <nav class="navbar navbar-inverse">
                    <div class="container-fluid">

                        <div class="navbar-header">
                            <a class="navbar-brand" href="{% url 'detail'%}">Clona PasteBin</a>
                        </div>

                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Account settings<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'logout' %}">Logout</a></li>
                                    <li><a href="{% url 'password_reset' %}">Reset Passoword</a></li>
                                </ul>
                            </li>

                            <li><a href="{% url 'pastes:paste_list'%}">Paste List</a></li>
                            <li><a href="{% url 'pastes:add_paste'%}">Paste Add</a></li>
                      </ul>
                    </div>
                </nav>
            {% else %}
                <h2>Login or register</h2>
                <nav class="navbar navbar-inverse">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="{% url 'detail'%}">Clona PasteBin</a>
                        </div>
                        <ul class="nav navbar-nav">
                            <li><a href="{% url 'login' %}">Login</a></li>
                            <li><a href="{% url 'user:register' %}">Register</a></li>
                        </ul>
                    </div>
                </nav>
            {% endif %}
        </div>    
        <br><br>
 
  <!--Scuza-mi aceasta parte de style, dar altfel nu-mi mergea schimbarile-->   
   
<style>
.navbar-inverse {
    background-color: rgb(22, 68, 90);
    border-color: aquamarine;
}

.navbar {
    position: relative;
    min-height: 50px;
    margin-bottom: 0;
    border: 3px solid transparent;
}

a {
    color: aqua;
}
#main {
    margin-top: 1px;
    padding: 1px;
    padding-left: 5px;
    padding-right: 15px;
    border-style: solid;
    border-color: rgb(15, 171, 243);
    text-align: center;
    background-color: rgb(104, 124, 238);
}
h2 {
    color: aqua;
}

body {
    background-color: burlywood;
}
</style>
</body>
</html>

server/pastes/templates/pastes/paste_add.html
<!DOCTYPE html>
{% load widget_tweaks %}
<html>
    <head>
        <title>Copia PasteBin</title>
        {% load static %}
        <link rel = "shourtcut icon" href = "{% static 'images/mr.png' %}" type = "mr/png">
        <link rel="stylesheet" href="{% static 'style/style.css' %}" type="text/css">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>

    <body>
        <div id = "main">
            <h2>Add Paste</h2>
            {% if user.is_authenticated %}
                <nav class="navbar navbar-inverse">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="{% url 'detail'%}">Clona PasteBin</a>
                        </div>

                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Account settings<span class="caret"></span></a>

                              <ul class="dropdown-menu">
                                <li><a href="{% url 'logout' %}">Logout</a></li>
                                <li><a href="{% url 'password_reset' %}">Reset Passoword</a></li>
                              </ul>

                            </li>

                            <li><a href="{% url 'pastes:paste_list'%}">Paste List</a></li>
                            <li><a href="{% url 'pastes:add_paste'%}">Paste Add</a></li>
                        </ul>
                    </div>
                </nav>

            {% else %}
                <a href="{% url 'login' %}">Login</a> 
                <a href="{% url 'user:register' %}">Register</a> 
            {% endif %}

        </div>

        <div id = "header">
            <div class = "form-group">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class = "btn btn-secondary">Paste Bin</button>
                </form>
            </div>
        </div>
    </body>

    
<style>

#header {
    margin-top: 5px;
    padding: 1px;
    padding-left: 5px;
    padding-right: 15px;
    background-color: rgb(14, 81, 112);
    border-style: solid;
    border-color: rgb(190, 222, 236);
    border-radius: 10px;
    text-align: center;
    font-size: 30px;
    width: auto;
    height: auto;
   
}
.navbar {
    position: relative;
    min-height: 50px;
    margin-bottom: 0;
    border: 3px solid transparent;
}
a {
    color: aqua;
}

#main {
    margin-top: 1px;
    padding: 1px;
    padding-left: 5px;
    padding-right: 15px;
    border-style: solid;
    border-color: rgb(15, 171, 243);
    text-align: center;
    background-color: rgb(104, 124, 238);
}
body {
    background-color: burlywood;
}
h2 {
    color: aqua;
}
</style>
</html>

server/pastes/templates/pastes/paste_detail.html
<!DOCTYPE html>
{% load widget_tweaks %}
{% load static %}
<html>
    <head>
        <title>Copia PasteBin</title>
        <link rel = "shourtcut icon" href = "{% static 'images/mr.png' %}" type = "mr/png">
        <link rel="stylesheet" href="{% static 'style/style.css' %}" type="text/css">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>

    <body>
        <div id = "main">
            <h1>Detail Pastes</h1>
            {% if user.is_authenticated %}
                <nav class="navbar navbar-inverse">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="{% url 'detail'%}">Clona PasteBin</a>
                        </div>

                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Account settings<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'logout' %}">Logout</a></li>
                                    <li><a href="{% url 'password_reset' %}">Reset Passoword</a></li>
                                </ul>
                            </li>

                            <li><a href="{% url 'pastes:paste_list'%}">Paste List</a></li>
                            <li><a href="{% url 'pastes:add_paste'%}">Paste Add</a></li>
                        </ul>
                    </div>
                </nav>
            {% endif %}
        </div>    
                
        <div id = "header">
            <h2>Titlu: {{ paste.title }}</h2> 
            <h2>By: {{paste.author}} </h2>
            <h3>Language: {{ paste.language }} </h3>
            <hr>
            <h3 id = "content">{{paste.content}}</h3>
        </div>
    </body>

<style>
    #content {
        color: rgb(17, 230, 176);
    }
  #header {
    margin-top: 5px;
    padding: 1px;
    padding-left: 5px;
    padding-right: 15px;
    background-color: rgb(14, 81, 112);
    border-style: solid;
    border-color: rgb(190, 222, 236);
    border-radius: 10px;
    text-align: center;
    font-size: 30px;
    width: auto;
    height: auto;
   
}
    .navigator {
    background-color:  rgb(22, 68, 90);
}
.navigator a:hover {
    background-color: #ddd;
    color: rgb(207, 78, 78);
}
a {
    color: aqua;
}
#main {
    margin-top: 1px;
    padding: 1px;
    padding-left: 5px;
    padding-right: 15px;
    border-style: solid;
    border-color: rgb(15, 171, 243);
    text-align: center;
    background-color: rgb(104, 124, 238);
}
h2 {
    color: aqua;
}
h3 {
    color: tomato;
}
</style>
</html>

server/pastes/templates/pastes/paste_list.html
<!DOCTYPE html>
{% load widget_tweaks %}
{% load static %}
<html>
    <head>
        <title>Copia PasteBin</title>
        <link rel = "shourtcut icon" href = "{% static 'images/mr.png' %}" type = "mr/png">
        <link rel="stylesheet" href="{% static 'style/style.css' %}" type="text/css">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>

    <body>
        <div id = "main">
            <h2>List Pastes</h2>
            {% if user.is_authenticated %}
                <nav class="navbar navbar-inverse">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="{% url 'detail'%}">Clona PasteBin</a>
                        </div>

                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Account settings
                                <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'logout' %}">Logout</a></li>
                                    <li><a href="{% url 'password_reset' %}">Reset Passoword</a></li>
                                </ul>
                            </li>

                            <li><a href="{% url 'pastes:paste_list'%}">Paste List</a></li>
                            <li><a href="{% url 'pastes:add_paste'%}">Paste Add</a></li>
                        </ul>
                    </div>
                </nav>

            {% else %}
                <a href="{% url 'login' %}">Login</a> 
                <a href="{% url 'user:register' %}">Register</a> 
            {% endif %}
        </div>
        
        <div id = "head">
            <ul>
                {% for paste in object_list %}
                <li>
                    <a href="{% url 'pastes:paste_detail' paste.pk %}"> 
                    {{paste.title }} </a> | {{paste.author}} <br>
                    {{paste.language}}
                <hr>
                </li>
                {% endfor %}
            </ul>
        </div>
    </body>

<style>

#head {
    margin-top: 5px;
    padding: 1px;
    padding-left: 5px;
    padding-right: 15px;
    background-color: rgb(14, 81, 112);
    border-style: solid;
    border-color: rgb(190, 222, 236);
    border-radius: 10px;
    font-size: 20px;
    width: auto;
    height: auto;
}
a {
    color: aqua;
}

#main {
    margin-top: 1px;
    padding: 1px;
    padding-left: 5px;
    padding-right: 15px;
    border-style: solid;
    border-color: rgb(15, 171, 243);
    text-align: center;
    background-color: rgb(104, 124, 238);
}
.navbar {
    position: relative;
    min-height: 50px;
    margin-bottom: 0;
    border: 3px solid transparent;
}
h2 {
    color: aqua;
}
body {
    background-color: burlywood;
}
</style>
</html>